### ISSUE TITLE
老师您好，这两个model加载文件，您并没有提供

### ISSUE THREAD

**Issue by GewelsJI** [JosephineRabbit/MLMSNet#3]
D_E.load_state_dict(torch.load('/home/rabbit/Desktop/D_E4epoch2.pkl'))
U.load_state_dict(torch.load('/home/rabbit/Desktop/U_4epoch2.pkl'))

而您提供的是encoder.pkl和decoder.pkl

感谢您百忙之中的回复

**Comment by JosephineRabbit** [comment]
D_E是encoder，U是decoder，抱歉我忘记改名了

**Comment by GewelsJI** [comment]
Traceback (most recent call last):
  File "/home/nercms/Documents/Gepeng-Ji/SOD-Code/[042]MLMSNet/update/MLMSNet-master/test.py", line 37, in <module>
    D_E.load_state_dict(torch.load("checkpoints/encoder.pkl"))  # '/home/rabbit/Desktop/D_E4epoch2.pkl'
  File "/home/nercms/anaconda2/envs/pytorch/lib/python3.5/site-packages/torch/serialization.py", line 358, in load
    return _load(f, map_location, pickle_module)
  File "/home/nercms/anaconda2/envs/pytorch/lib/python3.5/site-packages/torch/serialization.py", line 549, in _load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: storage has wrong size: expected 864691128455135234 got 512

**Comment by GewelsJI** [comment]
i got a new problem @JosephineRabbit

**Comment by JosephineRabbit** [comment]
Seems there's  some problem with the original checkpoints, I guess maybe it's broken when I copy it to a new machine. I re-trained the model and re-updated new checkpoints. Sorry for the problem.

**Comment by GewelsJI** [comment]
It seems have broken
```
/home/nercms/anaconda2/envs/pytorch-0.4.1/bin/python /media/nercms/NERCMS/GepengJi/SOD-code/MLMS/MLMSNet-master/test.py
Traceback (most recent call last):
  File "/media/nercms/NERCMS/GepengJi/SOD-code/MLMS/MLMSNet-master/test.py", line 36, in <module>
    D_E.load_state_dict(torch.load('./pre-trained/encoder.pkl', map_location="cuda:0"))  # encoder ('/home/rabbit/Desktop/D_E4epoch2.pkl')
  File "/home/nercms/anaconda2/envs/pytorch-0.4.1/lib/python3.6/site-packages/torch/nn/modules/module.py", line 719, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for DSS:
	Missing key(s) in state_dict: "base.0.weight", "base.0.bias", "base.2.weight", "base.2.bias", "base.5.weight", "base.5.bias", "base.7.weight", "base.7.bias", "base.10.weight", "base.10.bias", "base.12.weight", "base.12.bias", "base.14.weight", "base.14.bias", "base.17.weight", "base.17.bias", "base.19.weight", "base.19.bias", "base.21.weight", "base.21.bias", "base.24.weight", "base.24.bias", "base.26.weight", "base.26.bias", "base.28.weight", "base.28.bias", "feat.0.main.0.weight", "feat.0.main.0.bias", "feat.0.main.2.weight", "feat.0.main.2.bias", "feat.0.o.weight", "feat.0.o.bias", "feat.0.o2.weight", "feat.0.o2.bias", "feat.1.main.0.weight", "feat.1.main.0.bias", "feat.1.main.2.weight", "feat.1.main.2.bias", "feat.1.o.weight", "feat.1.o.bias", "feat.1.o2.weight", "feat.1.o2.bias", "feat.2.main.0.weight", "feat.2.main.0.bias", "feat.2.main.2.weight", "feat.2.main.2.bias", "feat.2.o.weight", "feat.2.o.bias", "feat.2.o2.weight", "feat.2.o2.bias", "feat.3.main.0.weight", "feat.3.main.0.bias", "feat.3.main.2.weight", "feat.3.main.2.bias", "feat.3.o.weight", "feat.3.o.bias", "feat.3.o2.weight", "feat.3.o2.bias", "feat.4.main.0.weight", "feat.4.main.0.bias", "feat.4.main.2.weight", "feat.4.main.2.bias", "feat.4.o.weight", "feat.4.o.bias", "feat.4.o2.weight", "feat.4.o2.bias", "feat.5.main.0.weight", "feat.5.main.0.bias", "feat.5.main.2.weight", "feat.5.main.2.bias", "feat.5.o.weight", "feat.5.o.bias", "feat.5.o2.weight", "feat.5.o2.bias", "up.0.weight", "up.0.bias", "up.1.weight", "up.1.bias", "up.2.weight", "up.2.bias", "up.3.weight", "up.3.bias", "up.4.weight", "up.4.bias", "up.5.weight", "up.5.bias", "up2.0.weight", "up2.0.bias", "up2.1.weight", "up2.1.bias", "up2.2.weight", "up2.2.bias", "up2.3.weight", "up2.3.bias", "up2.4.weight", "up2.4.bias", "up2.5.weight", "up2.5.bias". 
	Unexpected key(s) in state_dict: "module.base.0.weight", "module.base.0.bias", "module.base.2.weight", "module.base.2.bias", "module.base.5.weight", "module.base.5.bias", "module.base.7.weight", "module.base.7.bias", "module.base.10.weight", "module.base.10.bias", "module.base.12.weight", "module.base.12.bias", "module.base.14.weight", "module.base.14.bias", "module.base.17.weight", "module.base.17.bias", "module.base.19.weight", "module.base.19.bias", "module.base.21.weight", "module.base.21.bias", "module.base.24.weight", "module.base.24.bias", "module.base.26.weight", "module.base.26.bias", "module.base.28.weight", "module.base.28.bias", "module.feat.0.main.0.weight", "module.feat.0.main.0.bias", "module.feat.0.ed1.0.weight", "module.feat.0.ed1.0.bias", "module.feat.0.ed2.0.weight", "module.feat.0.ed2.0.bias", "module.feat.0.main3.0.weight", "module.feat.0.main3.0.bias", "module.feat.0.o.weight", "module.feat.0.o.bias", "module.feat.0.o2.weight", "module.feat.0.o2.bias", "module.feat.1.main.0.weight", "module.feat.1.main.0.bias", "module.feat.1.main.2.weight", "module.feat.1.main.2.bias", "module.feat.1.o.weight", "module.feat.1.o.bias", "module.feat.1.o2.weight", "module.feat.1.o2.bias", "module.feat.2.main.0.weight", "module.feat.2.main.0.bias", "module.feat.2.ed1.0.weight", "module.feat.2.ed1.0.bias", "module.feat.2.ed2.0.weight", "module.feat.2.ed2.0.bias", "module.feat.2.main3.0.weight", "module.feat.2.main3.0.bias", "module.feat.2.o.weight", "module.feat.2.o.bias", "module.feat.2.o2.weight", "module.feat.2.o2.bias", "module.feat.3.main.0.weight", "module.feat.3.main.0.bias", "module.feat.3.main.2.weight", "module.feat.3.main.2.bias", "module.feat.3.o.weight", "module.feat.3.o.bias", "module.feat.3.o2.weight", "module.feat.3.o2.bias", "module.feat.4.main.0.weight", "module.feat.4.main.0.bias", "module.feat.4.ed1.0.weight", "module.feat.4.ed1.0.bias", "module.feat.4.ed2.0.weight", "module.feat.4.ed2.0.bias", "module.feat.4.main3.0.weight", "module.feat.4.main3.0.bias", "module.feat.4.o.weight", "module.feat.4.o.bias", "module.feat.4.o2.weight", "module.feat.4.o2.bias", "module.feat.5.main.0.weight", "module.feat.5.main.0.bias", "module.feat.5.main.2.weight", "module.feat.5.main.2.bias", "module.feat.5.o.weight", "module.feat.5.o.bias", "module.feat.5.o2.weight", "module.feat.5.o2.bias", "module.e_feat.0.conv1.0.weight", "module.e_feat.0.conv1.0.bias", "module.e_feat.0.conv2.0.weight", "module.e_feat.0.conv2.0.bias", "module.e_feat.0.conv2.2.weight", "module.e_feat.0.conv2.2.bias", "module.e_feat.0.merge.weight", "module.e_feat.0.merge.bias", "module.e_feat.1.conv1.0.weight", "module.e_feat.1.conv1.0.bias", "module.e_feat.1.conv2.0.weight", "module.e_feat.1.conv2.0.bias", "module.e_feat.1.conv2.2.weight", "module.e_feat.1.conv2.2.bias", "module.e_feat.1.merge.weight", "module.e_feat.1.merge.bias", "module.e_feat.2.conv1.0.weight", "module.e_feat.2.conv1.0.bias", "module.e_feat.2.conv2.0.weight", "module.e_feat.2.conv2.0.bias", "module.e_feat.2.conv3.0.weight", "module.e_feat.2.conv3.0.bias", "module.e_feat.2.conv3.2.weight", "module.e_feat.2.conv3.2.bias", "module.e_feat.2.merge.weight", "module.e_feat.2.merge.bias", "module.e_feat.3.conv1.0.weight", "module.e_feat.3.conv1.0.bias", "module.e_feat.3.conv2.0.weight", "module.e_feat.3.conv2.0.bias", "module.e_feat.3.conv3.0.weight", "module.e_feat.3.conv3.0.bias", "module.e_feat.3.conv3.2.weight", "module.e_feat.3.conv3.2.bias", "module.e_feat.3.merge.weight", "module.e_feat.3.merge.bias", "module.e_feat.4.conv1.0.weight", "module.e_feat.4.conv1.0.bias", "module.e_feat.4.conv2.0.weight", "module.e_feat.4.conv2.0.bias", "module.e_feat.4.conv3.0.weight", "module.e_feat.4.conv3.0.bias", "module.e_feat.4.conv3.2.weight", "module.e_feat.4.conv3.2.bias", "module.e_feat.4.merge.weight", "module.e_feat.4.merge.bias", "module.up_e.0.weight", "module.up_e.0.bias", "module.up_e.1.weight", "module.up_e.1.bias", "module.up_e.2.weight", "module.up_e.2.bias", "module.up_e.3.weight", "module.up_e.3.bias", "module.up_e.4.weight", "module.up_e.4.bias", "module.up_sal.0.weight", "module.up_sal.0.bias", "module.up_sal.1.weight", "module.up_sal.1.bias", "module.up_sal.2.weight", "module.up_sal.2.bias", "module.up_sal.3.weight", "module.up_sal.3.bias", "module.up_sal.4.weight", "module.up_sal.4.bias", "module.up_sal.5.weight", "module.up_sal.5.bias", "module.up_sal.6.weight", "module.up_sal.6.bias", "module.up_sal_e.0.weight", "module.up_sal_e.0.bias", "module.up_sal_e.1.weight", "module.up_sal_e.1.bias", "module.up_sal_e.2.weight", "module.up_sal_e.2.bias", "module.up_sal_e.3.weight", "module.up_sal_e.3.bias", "module.up_sal_e.4.weight", "module.up_sal_e.4.bias", "module.up_sal_e.5.weight", "module.up_sal_e.5.bias", "module.up_sal_e.6.weight", "module.up_sal_e.6.bias", "module.fuse_e.weight", "module.fuse_e.bias". 

Process finished with exit code 1
```
@JosephineRabbit

**Comment by JosephineRabbit** [comment]
。。。朋友，你载入不对= =

**Comment by GewelsJI** [comment]
D_E.load_state_dict(torch.load('./pre-trained/encoder.pkl'))  # encoder ('/home/rabbit/Desktop/D_E4epoch2.pkl')
U.load_state_dict(torch.load('./pre-trained/decoder.pkl'))     # decoder ('/home/rabbit/Desktop/U_4epoch2.pkl')

**Comment by GewelsJI** [comment]
是这样载入对吗？

**Comment by JosephineRabbit** [comment]
pytorch多卡模型会带有module前缀。。。载入要去掉或者先吧模型定义成多卡=.=

**Comment by GewelsJI** [comment]
好的，这个模型是多卡，用的哪几张卡？
（您好，最近在研究您的论文，准备加入自己的论文对比，会引用您的这篇新作，如果方便的话，我们加个QQ聊一下可以吗？）（qq：778334697）

**Comment by JosephineRabbit** [comment]
不一定要哪几张呀，自己决定就好，单卡也可，只是定义时候用dataparallel做成多卡

**Comment by GewelsJI** [comment]
我先试试，谢谢老师
